# Production Docker Compose for Financial Multi-Agent Chatbot
# Uses environment variables from .env file
version: '3.8'

services:
  # Main application
  chatbot:
    build: .
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      # Force production settings
      - ENVIRONMENT=production
      - DEBUG=false
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - WORKERS=2
      - RELOAD=false
      # Production-specific overrides
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-financial-documents-prod}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT:-financial-chatbot-prod}
    volumes:
      - ./storage:/app/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - chatbot
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
